[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
task_manager = "8N5ugPhfbeMakrLqnqoAFHnVdWwjGLWMrQZSw9Ajathk"

[programs.devnet]
task_manager = "8N5ugPhfbeMakrLqnqoAFHnVdWwjGLWMrQZSw9Ajathk"  # Update this after deployment

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"  # Change to "devnet" for Devnet deployment, "localnet" for local testing
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
